### PR TITLE
Specify the path of multi_error to follow Rust 2018 rules

### PR DESCRIPTION
**Pull request by j-a-m-l**

### CODE REVIEW

**Comment by vorner** [comment]
Thank you. I'd just like to ask ‒ did this actually cause any practical trouble, or is it „just“ the correct syntax? I'm asking if I should add some other rust version into CI or something like that.

**Comment by j-a-m-l** [comment]
Yes, I was surprised that CI was OK, but I wasn't able to build the project (Rust 1.31.0).

**Comment by vorner** [comment]
I see. I think they made the paths somewhat more flexible in 1.32 which is what the CI run on. Now that 1.33 is out, I'll have to think about if it is time to guarantee some lowest version of rust, or if just „current stable“ as now.

**Comment by j-a-m-l** [comment]
Thanks for the clarification.

**Pull request merged**
